file_format: "1"

# Base keyboard
id: karma
name: Karma
type: shield
url: https://github.com/achyudh/karma
requires: [xiao_ble]
features:
  - keys
siblings:
  - karma_left
  - karma_right
  - karma_dongle
